cmake_minimum_required(VERSION 3.20)
project(ThreeVService LANGUAGES CXX)
find_package(Drogon CONFIG REQUIRED)
add_executable(ThreeVServiceRawSocket src/interfaces/raw_socket/main.cpp)
target_compile_features(ThreeVServiceRawSocket PRIVATE cxx_std_20)
target_compile_options(ThreeVServiceRawSocket PRIVATE -Wall -Wextra -Wpedantic)
if(WIN32)
    target_link_libraries(ThreeVServiceRawSocket PRIVATE ws2_32)
endif()
add_executable(ThreeVServiceBackend src/main.cpp)
target_compile_features(ThreeVServiceBackend PRIVATE cxx_std_20)
target_compile_options(ThreeVServiceBackend PRIVATE -Wall -Wextra -Wpedantic)
target_link_libraries(ThreeVServiceBackend PRIVATE Drogon::Drogon)